sudo: required
services:
- docker
branches:
  only:
  - master
env:
  global:
  - REGISTRY: registry.blackwoodseven.com
  - IMAGENAME: "$REGISTRY/$TRAVIS_REPO_SLUG"
  - TAG_VERSION: "$TRAVIS_BRANCH.$TRAVIS_BUILD_NUMBER"
  - TAG_LATEST: latest
  - secure: QEksHN2mX0tqcAWaHzf1RCAJOhYond9lgbY6PFdDEs2QdnRIHYQObGsM4CNt+7lYZGds0rF2j+QpxYKeIjRZh5oOkmLhx1Zgqvp+2sviZAckJx0bED2iE2QpKmHg0QeU+DbreTgHIbTXQrIR8fXYdDdxUw3Q4h7cuCX5b4TjWOlZK9Tjlag+avjhT+QeOiNCIE7LaIkFYBm04dT3Rp3Yv8fxdWiroMXEVeBkRO1VgEPh89NYghlqMUTljMjECQkXbjMcEpScVfMp4MOnXftNJ8DLhwTSgdUC3VrN9/5wDiLbEeFQ/grQ26I+MSCHjODRqejFij+A5N/OzPRbajrrF03ypdPEgXlvL+IF04LeOnO3kcAxcAKMMRpmPSTTJKO/PkoF7tMzOvDpfoZaBTxgWgjDdxJgvMNxeZWKc9QIzukUvloCE+ojtnS3jdTs8q2ZPxRGeVfH5AXnKqMH4NK5Lh1oQ1SH1x9tHYO90hM74CNOBEW6nMpRTYo3G2Y8HLXsrGVFkPHwIdS6gT/RBx1iJ0bSq/V0jgAVLFUJWJoyK8z8xcqNSjY55684twnfp7MyPfUzJc+qxq0lYAfuTEmdbQmrmNt+kJK62ioCLXmGbE9qoQk9Dll8Mh/jodCq+5hCknHQX8Jge8O9NsFYerw/oHvnUJZlM6t5gexhL8R+Uks=
before_script:
- docker login -u businesslogic -p "$REGISTRY_PASSWORD" $REGISTRY
- echo "LABEL GIT_COMMIT=$TRAVIS_COMMIT" >> Dockerfile
- echo "LABEL TAG_VERSION=$TAG_VERSION" >> Dockerfile
script:
- 'docker --version && docker-compose --version && make test && make compile && docker
  build $CACHE -t $IMAGENAME:$TAG_VERSION -t $IMAGENAME:$TAG_LATEST . && docker push
  $IMAGENAME:$TAG_VERSION && docker push $IMAGENAME:$TAG_LATEST '
after_success:
- 'git config --global user.email "tech@blackwoodseven.com" && git config --global
  user.name "Travis CI" && git tag -f $TAG_VERSION $TRAVIS_COMMIT && git push --tags
  && curl -G --data-urlencode "cause=$IMAGENAME:$TAG_VERSION build successfully on
  Travis" jenkins-buildtrigger.stage.blackwoodseven.com/?job=businesslogic-development\&token=bIsASXhoBfKaFHUrBBE7 '
after_failure:
- echo failed
notifications:
  slack:
    secure: jZpsZO/9xpOqME3hQHey7D3OTJFfC9Ca/xRTLKtavcmMJAmlJOPpu8S4xepl12n+/XodIlS9T+T+YTixWUDq2s/jCcjl62qY+Tuc6iu+lHAVmy0jcg/lpftVEoNCu/iU/+Eq3AAHHweTxjJD/XReQ5zhIFWzLrdNO4MtjOERRIcnt6nUiGCPE3JkSysXGinArwwQPReZ6wYDxb+u2h9Y9D5/8UFIbXzh3iI3yPL71M8vtgwbjMYU9N88ndwXyiJPFsJZHycx+1lAPoNY6pe5SFcSy4EcSGhczOQzmWDrz/UUWrMybYynYwefm79i4mGD59Vl8iivL8kj1Jaxr012oQs1PCMF1Y2heEYYn7xkJEi99Q29zm76/3gGONz9eiNmF5vrFWG6ujwWk0zB8kIsqKN/4YXeOFJDsWpHEY4Qi1yf4vWP7H0vR0/LML6ama+gjnS5UUzLB2QQcERACdMNN9jeWyfOXy2Aa81nAVmZiZf7TEm/T31hRrWIcXhEpoYq4/5jlaftobFDa3qtGehmvyHvQtB+sQuMBUWAB6Z93l9F4x/ofUZCjFVYPBwZ2w83vxwVEIWH/5B7WSjZyBevsk/QvRbc82mKqcdtBFHKoqcNDEs+f/7JbBkO+VU5Sze66MDxdz8RAPClnJ1ENrhQy+Dz+BnBthv3SyABgMn3uVg=
